# ####################### #
# # Steel Configuration # #
# ####################### #

# Enable verbose logging? (Good for debugging, but should be disabled in production)
verbose-logging: false

# Allow the plugin to submit anonymous usage statistics?
enable-metrics: true

# Allow the plugin to automatically update itself? (recommended so you can receive the newest API features)
enable-updater: true
